# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDbiUrPITmYj_OLnPm6VqZ9l0nSlgIeQ
"""

pip install tensorflow

import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import matplotlib.pyplot as plt

tf.keras.datasets.fashion_mnist.load_data()

(x_train, y_train),(x_test, y_test) = tf.keras.datasets.mnist.load_data()

y_train[2]

plt.imshow(x_train[2], cmap='grey')

x_train[1]

x_train, x_test = x_train / 255.0, x_test / 255.0

x_train[0]

model=models.Sequential ([
    layers.Flatten(input_shape=(28,28)),
    layers.Dense(128,activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

model.summary()

history=model.fit(x_train, y_train, epochs=5)

test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test accuracy:", test_acc)

predictions=model.predict(x_test)
print(predictions)
print('Prediction Shape - ', predictions.shape)

predictions[0]

print(np.argmax(predictions[0]))

plt.imshow(x_test[0], cmap='grey')

plt.imshow(x_test[1], cmap='gray')
plt.title(f"True Value : {y_test[10]}, Predicted Label: {np.argmax(predictions[10])}")
plt.show()

plt.plot(history.history['loss'], label='training label')
plt.xlabel('Epoch')
plt.ylabel('Label')
plt.title('Loss vs Epoch')
plt.legend()
plt.show()